### ISSUE TITLE
Cannot resize the logo

### ISSUE THREAD

**Issue by sogawa-sps** [NextJSTemplates/startup-nextjs#13]
It's not possible to resize the logo. When I change the "width" and "height" parameters, nothing happens. The logo stays the same size.

                <Image
                  src="/images/logo/logo-2.svg"
                  alt="logo"
                  width={140}
                  height={30}
                  className="w-full dark:hidden"
                />
                <Image
                  src="/images/logo/logo.svg"
                  alt="logo"
                  width={140}
                  height={30}
                  className="hidden w-full dark:block"
                />

**Comment by Zenesteria** [comment]
Hello there, these images have a parent container and as such have a max width restriction, if you wish to resize the images you can fiddle with the width set for the parent container, here's how:

`<div className="w-[PLACEHOLDER] max-w-full px-4 xl:mr-12">
              <Link
                href="/"
                className={`header-logo block w-full ${
                  sticky ? "py-5 lg:py-2" : "py-8"
                } `}
              >
                <Image
                  src="/images/logo/logo-2.svg"
                  alt="logo"
                  width={140}
                  height={30}
                  className="w-full dark:hidden"
                />
                <Image
                  src="/images/logo/logo.svg"
                  alt="logo"
                  width={140}
                  height={30}
                  className="hidden w-full dark:block"
                />
              </Link>
            </div>`
            
            where you see 'PLACEHOLDER' is where you can adjust to resize the image.
            
            HOPE IT HELPS!

**Comment by sogawa-sps** [comment]
Thank you so much!
