### ISSUE TITLE
Compact mode menu doesn't disappear after the click

### ISSUE THREAD

**Issue by sogawa-sps** [NextJSTemplates/startup-nextjs#14]
When the menu collapses to a "hamburger" icon in compact mode it stays on the screen when one opens it and clicks any of the menu items.

![image](https://github.com/NextJSTemplates/startup-nextjs/assets/36852014/37488bb0-1d28-4e51-8536-2d884d380ec3)

The issue reproduces only in a downloadable package and is not reproduced in an online live demo.

[startup-nextjs-main.zip](https://github.com/NextJSTemplates/startup-nextjs/files/13260022/startup-nextjs-main.zip)

**Comment by kamzar1** [comment]
Had the same issue.
There is one click action missing.
/components/header/index.tsx after approx. line 109 add:
                     ` onClick={() => navbarToggleHandler()}`

Original Code:                       
                   ` <li key={index} className="group relative">`
After modification:
``` 
<li key={index} className="group relative"
     onClick={() => navbarToggleHandler()}
>
```

**Comment by kamzar1** [comment]
Above comment only works with main menu items.
Clicking a submenu title will let the navbar hide as well.
Better solution would be placing it at both link divs:
/components/header/index.tsx
```
                        {menuItem.path ? (
                          <Link onClick={() => navbarToggleHandler()}
```

```
                              {menuItem.submenu.map((submenuItem, index) => (
                                <Link onClick={() => navbarToggleHandler()}
```

**Comment by Musharofchy** [comment]
Thanks for reporting, this has been resolved on V2
