### ISSUE TITLE
Direct links to the sections of the home page don't work

### ISSUE THREAD

**Issue by sogawa-sps** [NextJSTemplates/startup-nextjs#15]
If I try to open an exact section of the home page using the URL it doesn't work. The page always opens at the top. E.g.

`http://localhost:3000/#features`

Leads to the top of the home page.

However, if I try to navigate to it internally **within** the home page using the Link it works fine:

```
<Link
      href="/#features"
      className="inline-block rounded-sm bg-black px-8 py-4 text-base font-semibold text-white duration-300 ease-in-out hover:bg-black/90 dark:bg-white/10 dark:text-white dark:hover:bg-white/5"
>
Read More
</Link>
```

**Comment by Musharofchy** [comment]
This has been resolved on latest update
