### ISSUE TITLE
Colouring and positioning is off

### ISSUE THREAD

**Issue by Summerlytz** [NextJSTemplates/startup-nextjs#16]
Comparing my deployment (https://v2.web.bmrg.tech/) to the demo (https://startup.nextjstemplates.com/), the colouring is noticeably different, the buttons are not rounded, and the text positioning is different.

**Comment by Summerlytz** [comment]
@shafiqhammad5

**Comment by Musharofchy** [comment]
Can't access the demo, can you please explain a little more?
