### ISSUE TITLE
Generating new icons

### ISSUE THREAD

**Issue by nikonikolov** [NextJSTemplates/startup-nextjs#17]
I am looking at the svg icons in `components/Features/featuresData.tsx`. I want to use different icons, but keep the style. How were these icons generated? The nextjs documentation references [Material Design Icons](https://pictogrammers.com/library/mdi/), but the `layers` icon available there is definitely different from the one on the template.

Is there an easy way to take an icon from [Material Design Icons](https://pictogrammers.com/library/mdi/) or [Google Symbols and Icons](https://fonts.google.com/icons) and convert it to the style used in this template? Thanks

**Comment by Musharofchy** [comment]
Hey, try https://lineicons.com/icons/ or https://solaricons.com/ we have used icons from both packs
Thanks
