### ISSUE TITLE
I want to run the site 

### ISSUE THREAD

**Issue by heyturkiye204** [NextJSTemplates/startup-nextjs#18]
I want to run the site but I am getting various errors, please help me on Discord.

**Comment by Zenesteria** [comment]
hey there, can you share what error you're getting exactly?

**Comment by heyturkiye204** [comment]
3:53:18 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
3:53:18 PM: buildbot version: ecff8a8ea00a7123ac3111778469ca25529769de
3:53:18 PM: Fetching cached dependencies
3:53:18 PM: Failed to fetch cache, continuing with build
3:53:18 PM: Starting to prepare the repo for build
3:53:18 PM: No cached dependencies found. Cloning fresh repo
3:53:18 PM: git clone --filter=blob:none https://github.com/NextJSTemplates/startup-nextjs
3:53:19 PM: Preparing Git Reference refs/heads/main
3:53:21 PM: Starting to install dependencies
3:53:21 PM: Python version set to 3.8
3:53:21 PM: Attempting Ruby version 2.7.2, read from environment
3:53:22 PM: Using Ruby version 2.7.2
3:53:22 PM: Started restoring cached go cache
3:53:22 PM: Finished restoring cached go cache
3:53:22 PM: go version go1.19.13 linux/amd64
3:53:22 PM: Using PHP version 8.0
3:53:23 PM: v18.19.0 is already installed.
3:53:24 PM: Now using node v18.19.0 (npm v10.2.3)
3:53:24 PM: Enabling Node.js Corepack
3:53:24 PM: Started restoring cached build plugins
3:53:24 PM: Finished restoring cached build plugins
3:53:24 PM: Started restoring cached corepack dependencies
3:53:24 PM: Finished restoring cached corepack dependencies
3:53:24 PM: Installing npm packages using pnpm version 8.14.1
3:53:25 PM: Failed during stage "Install dependencies": dependency_installation script returned non-zero exit code: 1
3:53:25 PM:  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
3:53:25 PM: Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
3:53:25 PM:     Failure reason:
3:53:25 PM:     specifiers in the lockfile ({"@next/font":"13.1.6","eslint":"8.33.0","eslint-config-next":"13.1.6","next":"13.1.6","next-themes":"^0.2.1","react":"18.2.0","react-dom":"18.2.0","react-modal-video":"^2.0.0","@types/node":"^18.15.11","@types/react":"^18.0.34","autoprefixer":"^10.4.13","postcss":"^8.4.21","prettier":"^2.8.3","prettier-plugin-tailwindcss":"^0.2.2","tailwindcss":"^3.2.4","typescript":"^5.0.4"}) don"t match specs in package.json ({"@types/node":"^20.8.9","@types/react":"^18.2.33","autoprefixer":"^10.4.16","postcss":"^8.4.31","prettier":"^3.0.3","prettier-plugin-tailwindcss":"^0.5.6","tailwindcss":"^3.3.5","typescript":"^5.2.2","eslint":"8.33.0","eslint-config-next":"13.1.6","next":"^13.5.6","next-themes":"^0.2.1","react":"^18.2.0","react-dom":"^18.2.0","react-modal-video":"^2.0.0"})
Error during pnpm install
3:53:25 PM: Failing build: Failed to install dependencies
3:53:25 PM: Finished processing build request in 7.356s

I get this error when running the site on Netlify.

**Comment by Musharofchy** [comment]
Netlify doesnt support many features of Next.js, Try Static Exports option if you would like to deploy on netlify or deploy on vercel
