### ISSUE TITLE
Page anchor

### ISSUE THREAD

**Issue by kamzar1** [NextJSTemplates/startup-nextjs#19]
I got a local instance running, works well so far.
Links to other sites working fine, though how can I implement Page anchors?
I saw something linke https://startup.nextjstemplates.com/blog#0 how can that be made workable rolling to an anchor (div name div id)?
Thanks

**Comment by Musharofchy** [comment]
Hey, this is just an UI template for dynamic features such as pagination and dynamic blog. We recommend you upgrade to Startup Pro: https://nextjstemplates.com/templates/saas-starter-startup
