### ISSUE TITLE
hard reload not working in this template

### ISSUE THREAD

**Issue by ysaakpr** [NextJSTemplates/startup-nextjs#2]
I was trying to refresh using `ctrl + r` and even though the page reloads it doesn't goes to the top of page. And that should be the default behaviour of any standard web pages.

Another observation, I cant route to the section with id in the single page. Looks there is something causing this issue, but unfortunately i am unable to figure out the reason.

```
<Link href="#feature"> feature</Link>
<section id="feature"> </section>
```

This doesn't work

**Comment by shafiqhammad5** [comment]
@ysaakpr thanks for reporting.  Issue is solved
