### ISSUE TITLE
Hot Module Refresh Support

### ISSUE THREAD

**Issue by Metroidude** [NextJSTemplates/startup-nextjs#7]
Hello,

Hot module refresh is one of my favorite features. I spent a while modifying the template to match my needs, but I can't seem to get hot module refresh working. Can you assist? Shouldn't Next.js ship with it by default? Maybe I just didn't enable it correctly.

**Comment by workbee49** [comment]
@Metroidude did you resolve the issue?

**Comment by Metroidude** [comment]
Yes, thank you. Newbie mistake. I was compiling for production instead of using `npm run dev`
